chore: update terraform

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -10,21 +10,104 @@ permissions:
   contents: read
 
 jobs:
-  deploy-serverless:
-    name: Deploy Serverless in Amazon
+  terraform-ecr:
+    name: 'Create or Update Amazon ECR'
     runs-on: ubuntu-latest
     environment: production
+
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./terraform/ecr
+    env:
+      TF_VAR_name: ${{ vars.PROJECT_NAME }}
+
     steps:
-      - uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v1
         with:
-          node-version: ${{ matrix.node-version }}
-      - run: npm ci
-      - name: Serverless Deploy
-        uses: serverless/github-action@master
+          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+
+      - name: Terraform Init
+        run: ls && terraform init
+
+      - name: Terraform Format
+        run: terraform fmt -check
+
+      - name: Terraform Validate
+        run: terraform validate -no-color
+
+      - name: Terraform Plan
+        run: terraform plan -input=false
+        # env:
+        #   TF_VAR_ecr_registry: ${{ steps.login-ecr.outputs.registry }}
+
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
+
+      # - name: Terraform Apply
+      #   run: terraform apply -auto-approve -input=false
+
+  terraform-ecs:
+    name: 'Deploy ECS in Amazon'
+    runs-on: ubuntu-latest
+    needs: terraform-ecr
+    environment: production
+
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./terraform/infra
+    env:
+      TF_VAR_ecr_tag: ${{ github.sha }}
+      TF_VAR_ecr_repository: ${{ vars.PROJECT_NAME }}
+      TF_VAR_name: ${{ vars.PROJECT_NAME }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          args: deploy --stage devel
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v1
+        with:
+          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+
+      - name: Terraform Init
+        run: ls && terraform init
         env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          TF_VAR_ecr_registry: ${{ steps.login-ecr.outputs.registry }}=
+
+      - name: Terraform Format
+        run: terraform fmt -check
+
+      - name: Terraform Validate
+        run: terraform validate -no-color
+
+      # - name: Terraform Plan
+      #   run: terraform plan -input=false
+      #   env:
+      #     TF_VAR_ecr_registry: ${{ steps.login-ecr.outputs.registry }}
+
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      - name: Terraform Apply
+        run: terraform apply -auto-approve -input=false
+        env:
+          TF_VAR_ecr_registry: ${{ steps.login-ecr.outputs.registry }}
